//
//  AthleteEntries.swift
//  sportsApp
//
//  Created by Alvina Chow on 1/19/24.
//

import Foundation
import SwiftUI

let one_williams = Athlete(title: "Serena Williams", image: Image("Williams"), bday: "September 26, 1981", sport: "Tennis",
   desc: "Serena Williams is an iconic American tennis player whose impact on the sport extends far beyond the tennis court. Hailing from Saginaw, Michigan, Serena, alongside her sister Venus, transformed the landscape of women's tennis with her unparalleled athleticism and fierce determination.\n\nWith an astonishing 23 Grand Slam singles titles, Serena Williams is considered one of the greatest tennis players in history. Her powerful serve, aggressive playing style, and mental resilience have been key factors in her success. Williams achieved the prestigious Grand Slam in 2002-2003, winning all four major tournaments consecutively—a feat that showcased her dominance.\n\nBeyond her sporting achievements, Serena has been a trailblazer for gender equality in tennis, advocating for equal prize money and opportunities for female athletes. Her impact on and off the court has earned her respect and admiration globally. Despite facing adversity, injuries, and personal challenges, Serena's commitment to the game and her resilience have solidified her as an inspirational figure.\n\nOff the court, Serena Williams is a successful entrepreneur, fashion icon, and philanthropist. Her influence transcends sports, making her a symbol of empowerment and excellence for generations to come.")

let two_biles = Athlete(title: "Simone Biles", image: Image("Biles"), bday: "March 14, 1997", sport: "Gymnastics",
    desc: "Simone Biles is an American artistic gymnast renowned for her unparalleled athleticism, grace, and groundbreaking performances. Raised in Columbus, Ohio, Biles quickly rose to prominence in the gymnastics world with her exceptional skills and unmatched level of difficulty in routines.\n\nA four-time Olympic gold medalist, Biles made history at the 2016 Rio Olympics by showcasing her extraordinary talent and winning the individual all-around, vault, and floor exercise events. Her gravity-defying tumbling passes and innovative routines have set new standards in the sport. Biles continued her dominance at the 2020 Tokyo Olympics, where she further solidified her legacy by clinching additional gold medals.\n\nBeyond her incredible achievements, Simone Biles has been an advocate for mental health awareness and athlete well-being. In a courageous move, she withdrew from certain events at the Tokyo Olympics to prioritize her mental health, sparking important conversations about the pressures athletes face.\n\nAs a charismatic and inspirational figure, Biles has become a role model for aspiring gymnasts worldwide. Her impact extends beyond the gym, as she continues to break barriers, challenge norms, and redefine the possibilities for gymnastics excellence. Simone Biles stands as a symbol of resilience, strength, and courage in the world of sports.")

let three_ledecky = Athlete(title: "Katie Ledecky", image: Image("Ledecky"), bday: "March 17, 1997", sport: "Swimming",
    desc: "Katie Ledecky is an American competitive swimmer widely recognized for her exceptional talent and numerous achievements in the pool. A native of Bethesda, Maryland, Ledecky burst onto the international swimming scene with a remarkable performance at the 2012 London Olympics at the age of 15, where she clinched the gold medal in the 800-meter freestyle.\n\nKnown for her incredible endurance and dominance in distance events, Ledecky has set multiple world records in freestyle swimming. Her unparalleled success continued at the 2016 Rio Olympics, where she secured four gold medals and a silver, solidifying her status as one of the greatest female swimmers of her generation.\n\nLedecky's competitive spirit and dedication to her craft have earned her widespread admiration. Her impressive list of accomplishments includes numerous World Championship titles and Olympic gold medals, establishing her legacy as a true icon in the world of swimming. Beyond her athletic prowess, Katie Ledecky is also known for her humility, sportsmanship, and commitment to inspiring the next generation of swimmers. As she continues to make waves in the pool, Ledecky remains a beacon of excellence and a role model for aspiring athletes worldwide.")

let four_hamm = Athlete(title: "Mia Hamm", image: Image("Hamm"), bday: "March 17, 1972", sport: "Soccer",
    desc: "Mia Hamm is an American soccer legend who revolutionized women's soccer and left an indelible mark on the sport. Raised in Wichita Falls, Texas, Hamm's journey to becoming a soccer icon began at an early age. She rose to prominence as a key player on the United States women's national soccer team during the 1990s.\n\nHamm's exceptional skills, agility, and goal-scoring prowess contributed significantly to the success of the U.S. team. She played a pivotal role in leading the squad to two Olympic gold medals in 1996 and 2004 and two FIFA World Cup titles in 1991 and 1999. The latter victory, where Hamm's leadership and scoring ability were instrumental, remains a historic moment in women's soccer history.\n\nNot only did Mia Hamm excel on the international stage, but she also played a crucial role in popularizing women's soccer in the United States. Her impact transcended the field, inspiring a new generation of female athletes to pursue soccer and proving that women could excel at the highest levels of the sport.\n\nOff the field, Hamm has been involved in various charitable endeavors and remains a prominent figure in promoting gender equality in sports. Mia Hamm's legacy extends far beyond her playing days, as she continues to be a symbol of excellence, leadership, and empowerment in the world of soccer.")

let five_vonn = Athlete(title: "Lindsey Vonn", image: Image("Vonn"), bday: "October 18, 1984", sport: "Alpine Skiing",
    desc: "Lindsey Vonn is a retired American alpine ski racer who stands as one of the most successful and celebrated athletes in the history of alpine skiing. Hailing from St. Paul, Minnesota, Vonn's journey to greatness began at a young age, and she quickly rose through the ranks to become a dominant force on the slopes.\n\nKnown for her fearless and aggressive racing style, Lindsey Vonn achieved numerous milestones throughout her career. She clinched four overall World Cup titles and secured the title of the most successful American female alpine skier in history. Vonn's specialization in the speed events—downhill and super-G—earned her multiple World Championship gold medals and Olympic accolades.\n\nDespite facing injuries and setbacks, Vonn displayed remarkable resilience, often returning stronger than ever. Her charisma and competitive spirit endeared her to fans worldwide, making her a prominent figure in the world of winter sports.\n\nOff the slopes, Lindsey Vonn has been involved in philanthropy, empowering young athletes, and advocating for gender equality in sports. Her impact extends beyond her athletic achievements, solidifying her legacy as a trailblazer and role model for aspiring skiers and athletes globally. Lindsey Vonn's indomitable spirit and dedication have left an enduring mark on the sport of alpine skiing.")

let six_taurasi = Athlete(title: "Diana Turasi", image: Image("Turasi"), bday: "June 11, 1982", sport: "Basketball",
        desc: "Diana Taurasi is an American professional basketball player widely regarded as one of the greatest in the history of women's basketball. Originating from Chino, California, Taurasi's illustrious career has been marked by her scoring prowess, leadership, and numerous accolades.\n\nA standout player at the University of Connecticut, Taurasi led the Huskies to three consecutive NCAA championships from 2002 to 2004. Her exceptional skills and on-court intelligence translated seamlessly to the professional level when she entered the WNBA. Playing the majority of her career with the Phoenix Mercury, Taurasi has accumulated multiple WNBA championships and earned numerous All-Star and MVP honors.\n\nDiana Taurasi's impact extends beyond domestic play, as she has been a key figure on the international stage. Representing the United States, she has contributed to multiple Olympic gold medals and World Championship victories, solidifying her status as one of the most accomplished and decorated players in the sport.\n\nKnown for her competitive spirit and clutch performances, Taurasi's influence on women's basketball goes beyond statistics. Her leadership on and off the court, coupled with a relentless work ethic, has inspired aspiring athletes and earned her a place among the legends of the game. Diana Taurasi's enduring legacy is that of a trailblazer and a basketball icon.")

let seven_felix = Athlete(title: "Allyson Felix", image: Image("Felix"), bday: "November 18, 1985", sport: "Track and Field", 
      desc: "Allyson Felix is an American track and field athlete whose remarkable speed and versatility have made her one of the most decorated Olympians in history. Hailing from Los Angeles, California, Felix has achieved success in various sprint events and relays, showcasing her exceptional talent and dedication to the sport.\n\nFelix first gained widespread recognition at the 2004 Athens Olympics, where she clinched a silver medal in the 200 meters. Her illustrious career includes an impressive collection of Olympic and World Championship gold medals in the 200 meters, 4x100 meters relay, and 4x400 meters relay. Known for her smooth stride and explosive speed, Felix's dominance on the track has made her a symbol of excellence in sprinting.\n\nBeyond her athletic achievements, Allyson Felix has been a vocal advocate for gender equality and the rights of athletes. Her courage in addressing issues such as maternity rights and fair compensation for female athletes has had a significant impact on the conversation surrounding women in sports.\n\nFelix's journey as a mother and athlete, coupled with her on-track success, has inspired many and solidified her as a role model. Her resilience, sportsmanship, and commitment to advocacy make Allyson Felix not only a track and field legend but also a powerful force for positive change in the world of sports.")

let eight_king = Athlete(title: "Billie Jean King", image: Image("King"), bday:"November 22, 1943", sport: "Tennis",
    desc: "Billie Jean King is an American tennis legend and a trailblazer for gender equality in sports. Hailing from Long Beach, California, King's impact on the tennis court and her advocacy for social change have left an enduring legacy.\n\nA 39-time Grand Slam title winner, Billie Jean King's illustrious career includes victories in singles, doubles, and mixed doubles. Her iconic 'Battle of the Sexes' match against Bobby Riggs in 1973 became a pivotal moment in sports history, as King's win solidified the importance of women's tennis and challenged traditional gender norms.\n\nOff the court, King has been a tireless advocate for gender equality and LGBTQ+ rights. She played a pivotal role in the formation of the Women's Tennis Association (WTA) and has consistently fought for equal prize money and opportunities for female athletes. King's leadership and commitment to social justice have transcended tennis, making her a symbol of empowerment for women in sports.\n\nIn recognition of her contributions, Billie Jean King has received numerous awards, including the Presidential Medal of Freedom. Her legacy extends far beyond her playing days, as she continues to inspire and pave the way for future generations of athletes to strive for excellence and equality.")

let nine_jennings = Athlete(title: "Kerri Walsh Jennings", image: Image("Jennings"), bday: "August 15, 1978", sport: "Beach Volleyball",
    desc: "Kerri Walsh Jennings is an American beach volleyball player whose dynamic athleticism and unparalleled success have made her one of the most accomplished and iconic figures in the sport. Hailing from Santa Clara, California, Walsh Jennings has left an indelible mark on beach volleyball with her dominant performances and numerous accolades.\n\nTeaming up with Misty May-Treanor, Walsh Jennings achieved unprecedented success in the beach volleyball scene. The duo secured three consecutive Olympic gold medals at the 2004 Athens, 2008 Beijing, and 2012 London Games, establishing themselves as one of the greatest pairs in the history of the sport. Walsh Jennings's formidable net skills, powerful spikes, and strategic prowess contributed significantly to their success.\n\nBeyond her Olympic triumphs, Walsh Jennings continued to be a force on the international stage, amassing multiple World Championship titles and numerous victories on the AVP and FIVB tours. Her longevity in the sport and ability to adapt to different partners showcased her versatility and enduring commitment to excellence.\n\nOff the sand, Kerri Walsh Jennings is recognized for her sportsmanship and dedication to promoting a healthy and active lifestyle. Her impact extends beyond the volleyball court, as she remains an inspiration to aspiring athletes and a symbol of resilience, teamwork, and success in beach volleyball.")

let ten_kim = Athlete(title: "Chloe Kim", image: Image("Kim"), bday: "April 23, 2000", sport: "Snowboarding",
    desc: "Chloe Kim is an American snowboarder who has rapidly risen to prominence as one of the most talented and accomplished athletes in her sport. Hailing from Torrance, California, Kim's remarkable achievements on the halfpipe have made her a trailblazer in snowboarding.\n\nAt just 17 years old, Chloe Kim made history at the 2018 Winter Olympics in Pyeongchang, South Korea. She captured the gold medal in the women's snowboard halfpipe with a stunning performance, becoming the youngest woman to win an Olympic snowboarding medal. Kim's exceptional amplitude, technical skills, and stylish flair on the halfpipe set her apart from her competitors.\n\nBeyond her Olympic success, Chloe Kim has consistently dominated the snowboarding scene, clinching multiple X Games titles and World Championship medals. Her fearless and progressive approach to the sport, including being the first woman to land back-to-back 1080 spins in competition, has redefined women's snowboarding.\n\nOff the slopes, Chloe Kim is known for her charismatic personality and advocacy for diversity and inclusion in winter sports. Her impact extends beyond her athletic prowess, making her a role model for aspiring snowboarders and a symbol of the next generation of excellence in winter sports.")

let eleven_zhang = Athlete(title: "Rose Zhang", image: Image("Zhang"), bday: "May 24, 2003", sport: "Golf",
    desc: "Rose Zhang has solidified her place as an accomplished American professional golfer, making significant strides in both the amateur and professional circuits. Hailing from Arcadia, California, Zhang's journey in golf commenced at the age of 9, and her early prowess earned her recognition as the world's top amateur female golfer during her time at Pacific Academy.\n\nZhang's amateur career is marked by remarkable achievements, including winning the 2020 U.S. Women's Amateur and clinching consecutive NCAA Division I Championships in 2022 and 2023—making her the first woman to achieve this feat. Her talent also shone internationally as part of the gold medal-winning U.S. team at the 2019 Pan American Games.\n\nIn April 2023, Zhang secured victory at the Augusta National Women's Amateur, adding to her extensive list of accomplishments. Known for her exceptional golf swing, she holds the women's course record at Pebble Beach Golf Links, a testament to her skill and precision.\n\nTransitioning to the professional realm in June 2023, Zhang made an immediate impact by winning the Mizuho Americas Open on the LPGA Tour, becoming the first player since 1951 to win in her professional debut. With numerous accolades, a historic winning record, and a rising status in the world rankings, Rose Zhang stands as a golf prodigy poised for a remarkable career on the international stage.")

let twelve_gauff = Athlete(title: "Coco Gauff", image: Image("Gauff"), bday: "March 13, 2004", sport: "Tennis",
   desc: "Coco Gauff is an American professional tennis player who burst onto the international scene with her exceptional talent and maturity on the court. Born in Delray Beach, Florida, Gauff's rise in tennis began at an early age, drawing attention for her impressive skills and composure.\n\nGauff gained widespread recognition at the 2019 Wimbledon Championships, where, as a 15-year-old qualifier, she defeated Venus Williams in the first round, making her the youngest player to win a match at Wimbledon since 1991. Her spirited run continued, reaching the fourth round and solidifying her status as a tennis prodigy.\n\nRenowned for her aggressive playing style, powerful groundstrokes, and exceptional court coverage, Coco Gauff has consistently made waves in the tennis world. Her notable achievements include competing in Grand Slam events, representing the United States in Fed Cup competitions, and clinching her inaugural WTA singles title in 2019. In a defining moment in 2023, Gauff secured her first major singles title as the US Open champion, further cementing her status as a promising rising star in tennis.\n\nOff the court, Gauff has been an advocate for social justice, using her platform to address issues such as racial inequality and police brutality. Her poised demeanor, both on and off the court, has made her a role model for aspiring athletes and a symbol of the new generation shaping the future of tennis.")

let thirteen_clark = Athlete(title: "Caitlin Clark", image: Image("Clark"), bday: "January 22, 2002", sport: "Basketball",
     desc: "Caitlin Clark is an emerging American basketball phenom known for her exceptional skills and dynamic style of play. An Iowa native, Clark made a significant impact on the basketball scene during her collegiate career at the University of Iowa.\n\nAs a standout point guard, Clark quickly garnered attention for her scoring ability, court vision, and playmaking prowess. In her freshman season (2020-2021), she became one of the leading scorers in women's college basketball, showcasing her versatility with impressive scoring averages and numerous triple-doubles.\n\nClark's electrifying performances earned her all sorts of accolades and recognition, including the AP Player of the Year, the Honda Sports Award, the John R. Wooden Award, Naismith College Player of the Year, USBWA National Player of the Year, and the Wade Trophy. She is projected to be the first overall pick in the 2024 WNBA draft. Her ability to take control of games and make clutch plays has drawn comparisons to some of the greatest players in the sport.\n\nBeyond her on-court achievements, Caitlin Clark's impact extends to her role as a charismatic and influential figure in women's basketball. As she continues to shape her promising career, Clark stands out as a player to watch and a symbol of the evolving landscape of women's collegiate basketball. Her dedication, skill set, and leadership qualities mark her as a rising star in the world of basketball.")

let fourteen_thompson = Athlete(title: "Alyssa Thompson", image: Image("Thompson"), bday: "November 7, 2004", sport: "Soccer",
    desc: "Alyssa Thompson has swiftly emerged as a rising star in American professional soccer. As a forward for NWSL team Angel City FC and the United States women's national team, Thompson's exceptional skills have garnered widespread recognition. In 2021, she earned the prestigious title of Gatorade Player of the Year, showcasing her prowess and impact on the field.\n\nRaised in Studio City, California, Thompson's journey in soccer began at an early age, displaying remarkable talent that led to her racing against boys and excelling. Her commitment to excellence saw her playing on boys' teams and competing at a high level with players older than her. Despite facing challenges, she continued to shine, scoring an impressive 48 goals during her freshman and sophomore years at Harvard-Westlake School.\n\nThompson's professional journey took a significant turn when Angel City FC selected her as the first overall pick, making her essentially the most expensive player in league history. Thompson's impact was immediate, scoring in her professional debut while still attending her senior year of high school. Her remarkable achievements have extended to the international stage, representing the United States with distinction and earning a call-up to the senior national team, where she made her debut at Wembley Stadium.\n\nAs she continues to make waves in both domestic and international soccer, Alyssa Thompson stands as a symbol of talent, tenacity, and trailblazing success.")

let fifteen_mclaughlin = Athlete(title: "Sydney McLaughlin-Levrone", image: Image("McLaughlin"), bday: "August 7, 1999", sport: "Track and Field",
    desc: "Sydney McLaughlin-Levrone is an American track and field athlete specializing in hurdling and sprinting. Born in New Brunswick, New Jersey, McLaughlin gained international acclaim for her exceptional talent and achievements in the world of athletics.\n\nMcLaughlin-Levrone first captured global attention during the 2016 Rio Olympics, where, at the age of 17, she became the youngest U.S. track and field Olympian in decades. Her career continued to soar, and she became a dominant force in women's hurdling.\n\nSydney McLaughlin-Levrone's remarkable performances continued at the 2020 Tokyo Olympics, where she clinched the gold medal in the 400-meter hurdles. At the 2022 World Championships, she set the 400-meter hurdles world record once again with a time of 50.68 seconds. Known for her speed, agility, and technical precision over hurdles, McLaughlin's achievements have reshaped the landscape of women's track and field.\n\nOff the track, McLaughlin-Levrone is recognized for her dedication to her faith, humility, and advocacy for mental health awareness. As a trailblazer and role model, Sydney McLaughlin-Levrone stands as a symbol of excellence, breaking barriers, and inspiring future generations of athletes worldwide.")
