//
//  GearEntries.swift
//  sportsApp
//
//  Created by Alvina Chow on 1/26/24.
//

import Foundation
import SwiftUI

let one_sportsBra = Gear(title: "Sports Bras", image: Image("SportsBra") ,
    desc: "Sports bras stand as essential companions in the realm of sports for girls, seamlessly blending comfort, support, and performance. Tailored to meet the unique anatomical and biomechanical needs of female athletes, these bras provide a level of support crucial for engaging in various physical activities.\n\nCrafted from breathable, moisture-wicking fabrics, sports bras keep girls comfortable by managing perspiration during workouts or sports matches. Their design minimizes breast movement, offering stability and preventing discomfort or potential damage to breast tissue, especially in high-impact sports.\n\nBeyond functionality, sports bras contribute to confidence and focus. Their secure fit ensures that girls can move freely without the distraction of discomfort or self-consciousness, allowing them to fully immerse themselves in the athletic experience.\n\nWhether it's running, jumping, or participating in team sports, sports bras come in various styles and impact levels to cater to different preferences and activity levels.")

let two_tampon = Gear(title: "Tampon", image: Image("Tampon"),
  desc: "Tampons play a pivotal role in supporting active girls during their menstrual cycles, offering a discreet and reliable solution for managing menstrual flow while participating in sports. Compact and designed for comfort, tampons provide a level of freedom that traditional menstrual products may not.\n\nTailored for an athletic lifestyle, tampons are inserted into the vagina, allowing for unencumbered movement during physical activities like running, swimming, or team sports. Their discreet nature ensures that young athletes can focus on their performance without the worry of visible signs of menstruation.\n\nTampons are available in various absorbency levels, accommodating different flow patterns and activity intensities. This flexibility empowers girls to choose the right tampon for their specific needs, ensuring both comfort and confidence during sports engagements.\n\nIn addition to their practical benefits, tampons contribute to a sense of normalcy around menstruation. By incorporating tampons into their routine, girls can navigate their menstrual cycles seamlessly, fostering a positive and inclusive environment in the world of sports.")

let three_shorts = Gear(title: "Compression Shorts", image: Image("Shorts"),
    desc: "Compression shorts are a vital piece of sports gear specifically designed to optimize performance and provide essential support for girls engaged in various physical activities. Crafted from elastic materials, these shorts snugly wrap around the thighs and buttocks, offering compression to the muscles. The primary purpose of compression shorts is to enhance blood circulation and reduce muscle vibration during movement, ultimately minimizing fatigue and promoting quicker recovery.\n\nIn the context of sports, compression shorts prove invaluable for their ability to provide targeted support to the major muscle groups involved in activities such as running, cycling, or weightlifting. The snug fit also helps prevent chafing and irritation, ensuring a comfortable experience throughout intense workouts.\n\nThe moisture-wicking properties of compression shorts contribute to effective sweat management, keeping the body cool and dry. This feature is particularly advantageous during high-intensity exercises, allowing girls to maintain focus on their performance without the distraction of discomfort.")

let four_headbands = Gear(title: "Headband", image: Image("Headband"),
      desc: "Headbands emerge as essential athletic accessories, seamlessly blending style with functionality to enhance the sports experience for girls. Designed to keep hair in place and manage perspiration, these simple yet effective bands play a crucial role in maintaining focus and comfort during physical activities.\n\nCrafted from moisture-wicking materials, headbands efficiently absorb sweat, preventing it from dripping into the eyes and disrupting concentration. This proves particularly advantageous during intense workouts or sports matches, allowing girls to keep their vision clear and perform at their best.\n\nBeyond their moisture-controlling prowess, headbands contribute to a streamlined appearance, ensuring that hair stays off the face. This not only minimizes distractions but also enhances safety, especially in sports where visibility is key.\n\nWhether it's a high-impact cardio session, a soccer match, or a yoga class, headbands offer a lightweight and stylish solution to hair management. With a variety of designs and materials available, girls can personalize their sports attire while benefiting from the practical advantages of this unassuming yet indispensable accessory.")
