//
//  GearEntries.swift
//  sportsApp
//
//  Created by Alvina Chow on 1/26/24.
//

import Foundation
import SwiftUI

let one_sportsBra = Gear(title: "Sports Bra", image: Image("SportsBra") ,
    desc: "Sports bras stand as essential companions in the realm of sports for girls, seamlessly blending comfort, support, and performance. Tailored to meet the unique anatomical and biomechanical needs of female athletes, these bras provide a level of support crucial for engaging in various physical activities.\n\nCrafted from breathable, moisture-wicking fabrics, sports bras keep girls comfortable by managing perspiration during workouts or sports matches. Their design minimizes breast movement, offering stability and preventing discomfort or potential damage to breast tissue, especially in high-impact sports.\n\nBeyond functionality, sports bras contribute to confidence and focus. Their secure fit ensures that girls can move freely without the distraction of discomfort or self-consciousness, allowing them to fully immerse themselves in the athletic experience.\n\nWhether it's running, jumping, or participating in team sports, sports bras come in various styles and impact levels to cater to different preferences and activity levels.")

let two_tampon = Gear(title: "Menstrual Products", image: Image("Tampon"),
  desc: "Menstrual products play a vital role in supporting girls' participation in sports, addressing a natural aspect of their physiology with comfort and convenience. In the context of sports, where physical activity and performance are paramount, menstrual products provide girls with the assurance and freedom to pursue their athletic passions without concerns about discomfort or leaks.\n\nTampons, pads, and menstrual cups offer flexibility to accommodate individual preferences and varying levels of physical activity. Modern menstrual products are designed to provide discreet and reliable protection, allowing girls to focus on their performance rather than worry about their menstrual cycle.\n\nPromoting accessibility and open discussions about menstrual health in sports is crucial for breaking down stigma and normalizing conversations. By creating an environment where girls feel supported and equipped with the right products, sports organizations contribute to the overall well-being and inclusivity of female athletes. This inclusivity, in turn, encourages girls to stay active, fostering a positive relationship between menstruation and sports and reinforcing the message that every aspect of their health is valued in the pursuit of their athletic goals.")

let three_shorts = Gear(title: "Compression Shorts", image: Image("Shorts"),
    desc: "Compression shorts are a vital piece of sports gear specifically designed to optimize performance and provide essential support for girls engaged in various physical activities. Crafted from elastic materials, these shorts snugly wrap around the thighs and buttocks, offering compression to the muscles. The primary purpose of compression shorts is to enhance blood circulation and reduce muscle vibration during movement, ultimately minimizing fatigue and promoting quicker recovery.\n\nIn the context of sports, compression shorts prove invaluable for their ability to provide targeted support to the major muscle groups involved in activities such as running, cycling, or weightlifting. The snug fit also helps prevent chafing and irritation, ensuring a comfortable experience throughout intense workouts.\n\nThe moisture-wicking properties of compression shorts contribute to effective sweat management, keeping the body cool and dry. This feature is particularly advantageous during high-intensity exercises, allowing girls to maintain focus on their performance without the distraction of discomfort.")

let four_headbands = Gear(title: "Headband", image: Image("Headband"),
      desc: "Headbands emerge as essential athletic accessories, seamlessly blending style with functionality to enhance the sports experience for girls. Designed to keep hair in place and manage perspiration, these simple yet effective bands play a crucial role in maintaining focus and comfort during physical activities.\n\nCrafted from moisture-wicking materials, headbands efficiently absorb sweat, preventing it from dripping into the eyes and disrupting concentration. This proves particularly advantageous during intense workouts or sports matches, allowing girls to keep their vision clear and perform at their best.\n\nBeyond their moisture-controlling prowess, headbands contribute to a streamlined appearance, ensuring that hair stays off the face. This not only minimizes distractions but also enhances safety, especially in sports where visibility is key.\n\nWhether it's a high-impact cardio session, a soccer match, or a yoga class, headbands offer a lightweight and stylish solution to hair management. With a variety of designs and materials available, girls can personalize their sports attire while benefiting from the practical advantages of this unassuming yet indispensable accessory.")

let five_hydration = Gear(title: "Hydration Products", image: Image("Hydration"),
    desc: "Hydration is a cornerstone of athletic performance, and for girls in sports, maintaining optimal fluid balance is essential for sustained energy, focus, and overall well-being. Hydration products, including sports drinks, water bottles, and electrolyte supplements, play a pivotal role in supporting girls during physical activities.\n\nIn the dynamic world of sports, where girls often engage in rigorous training and competition, effective hydration is key to preventing dehydration, fatigue, and potential health risks. Sports drinks with electrolytes help replenish lost minerals during intense exercise, while water bottles offer a convenient and accessible way to stay hydrated on the go.\n\nEncouraging girls to adopt healthy hydration habits contributes to their physical resilience and mental acuity. Coaches, parents, and sports organizations can emphasize the importance of regular fluid intake, fostering a culture where staying hydrated is an integral part of athletic preparation.\n\nHydration products not only aid in physical performance but also serve as a reminder of the value placed on athletes' well-being. By prioritizing hydration in sports, girls are more likely to enjoy a positive and sustained experience, enhancing their motivation to stay active, compete, and achieve their athletic goals.\n\nWhether it's on the track, in the gym, or on the field, compression shorts are a go-to choice for athletes aiming for enhanced muscle support, reduced muscle soreness, and an overall improved experience during physical exertion.")

let six_helmets = Gear(title: "Helmet", image: Image("Helmet"),
   desc: "Helmets are indispensable protective gear, playing a pivotal role in ensuring the safety and well-being of girls participating in sports. Designed to mitigate the risk of head injuries, helmets are especially crucial in contact sports such as football, hockey, and lacrosse, where collisions and impacts are inherent to the game. For girls engaged in activities like cycling, skateboarding, or rollerblading, helmets provide a vital layer of defense against potential head injuries during falls or accidents.\n\nThe significance of helmets extends beyond physical protection; they instill confidence in girls and their parents, fostering a sense of security that encourages continued participation in sports. As safety remains a paramount concern, modern helmets are engineered with advanced materials and technologies to provide optimal impact absorption and fit.\n\nEnsuring that girls have access to well-fitted, quality helmets tailored to their specific sports is essential for promoting their long-term involvement in physical activities. By prioritizing safety through proper headgear, parents, coaches, and sports organizations contribute to creating a supportive environment that empowers girls to pursue their athletic passions with confidence and enthusiasm. Helmets not only safeguard against potential risks but also serve as a symbol of commitment to fostering a culture of well-being and enjoyment in sports for girls.")

let seven_mouthguard = Gear(title: "Mouthguard", image: Image("Mouthguard"),
    desc: "Mouthguards are indispensable accessories in the realm of sports, offering a critical layer of protection for girls engaged in various athletic pursuits. These custom-fitted guards, typically made of durable materials like silicone or ethylene vinyl acetate, serve as a barrier against potential dental injuries, concussions, and facial trauma during sports activities. In contact sports like soccer, basketball, or field hockey, where accidental collisions and impacts are inherent, mouthguards become essential safeguards for oral health.\n\nFor girls participating in sports, mouthguards play a pivotal role in not only preserving their smiles but also in instilling confidence. By reducing the risk of dental injuries, these protective devices encourage continued participation, promoting a positive and secure sports experience. Beyond the physical aspect, mouthguards contribute to the overall well-being of young athletes, allowing them to focus on skill development and teamwork without the distraction of potential injuries.\n\nAs a standard piece of athletic gear, mouthguards signify a commitment to safety in sports. Ensuring that girls have access to well-fitted, quality mouthguards tailored to their specific activities reinforces a culture of protection, encouraging their sustained engagement in sports with enthusiasm and a focus on long-term health and enjoyment.")

let eight_safetyPads = Gear(title: "Safety Pads", image: Image("Pads"),
    desc: "Safety pads are indispensable allies for girls in sports, serving as a comprehensive shield against impact-related injuries and ensuring a secure and resilient sporting experience. Designed to protect vulnerable areas like elbows, wrists, and shins, these pads are crafted from durable materials such as foam, gel, or high-impact-resistant plastics.\n\nIn dynamic sports like skateboarding, rollerblading, or biking, where falls and collisions are inherent, safety pads become crucial safeguards, minimizing the risk of fractures, bruises, and abrasions. By offering a layer of protection without compromising mobility, safety pads empower girls to push their limits, build confidence, and explore their athletic potential.\n\nThe significance of safety pads extends beyond the physical realm, playing a pivotal role in fostering a positive sports culture. Parents, coaches, and sports organizations advocating for the use of safety pads prioritize the well-being of young athletes, creating an environment that encourages girls to stay active and engaged in sports with reduced apprehension.\n\nAs a symbol of commitment to safety, safety pads contribute to a culture that values the long-term health and enjoyment of girls in sports. Ensuring access to well-fitted, quality safety pads tailored to specific activities reinforces a holistic approach to injury prevention, allowing girls to pursue their athletic passions with resilience and enthusiasm.")

let nine_braces = Gear(title: "Braces", image: Image("Brace"),
   desc: "Braces serve as crucial support for girls engaged in sports, offering stability and protection to joints susceptible to injury during physical activities. Whether it's knee braces, ankle braces, or wrist braces, these orthopedic devices play a vital role in preventing injuries and promoting longevity in sports participation.\n\nIn high-impact sports like soccer, basketball, or volleyball, where sudden movements and abrupt stops are common, knee braces provide essential reinforcement, reducing the risk of ligament strains and tears. Ankle braces, on the other hand, offer support against twists and sprains, enhancing stability during rapid lateral movements. Wrist braces can be invaluable in sports involving hand use, protecting against strains and impact-related injuries.\n\nBeyond physical protection, braces contribute significantly to the mental resilience of female athletes. By instilling confidence in the stability of joints, braces empower girls to push their boundaries, take on challenges, and pursue their athletic passions without the fear of injury.\n\nSports organizations, coaches, and parents promoting the use of braces underscore a commitment to the well-being and sustained participation of girls in sports. By incorporating braces into the sports culture, girls are more likely to feel supported, reducing the likelihood of injuries and enhancing their overall experience, thus encouraging them to stay active and engaged in sports.")

let ten_footwear = Gear(title: "Footwear", image: Image("Footwear"),
    desc: "Footwear is a cornerstone of athletic performance for girls in sports, playing a pivotal role in providing comfort, support, and protection. Whether it's running shoes, cleats, or court shoes, the right footwear is essential for preventing injuries, enhancing performance, and ensuring a positive sports experience.\n\nIn sports like soccer, where agility and quick directional changes are crucial, well-fitted cleats offer optimal traction and stability on the field. Running shoes provide cushioning and shock absorption for activities like track and field or cross country, reducing the impact on joints during high-impact movements. Court shoes are designed to provide grip and support for sports like basketball and volleyball, where lateral movements and sudden stops are frequent.\n\nThe significance of proper footwear extends beyond the physical realm, influencing girls' confidence and overall enjoyment in sports. Well-designed and appropriate shoes contribute to a sense of security, allowing girls to focus on skill development and competition without discomfort or distraction.\n\nSports organizations, coaches, and parents can positively impact girls' sports experiences by emphasizing the importance of quality footwear. By ensuring access to the right shoes tailored to specific activities, they contribute to creating a supportive environment that encourages girls to stay active, pursue their athletic passions, and foster a lifelong love for sports.")
