//
//  SportEntries.swift
//  sportsApp
//
//  Created by Alvina Chow on 1/22/24.
//

import Foundation
import SwiftUI


let one_rugby = Sport(title: "Rugby", image: Image("Rugby"), year: "1500s", loc: "England",
    desc: "Rugby, a dynamic collision of skill, strategy, and camaraderie, has evolved into a globally cherished team sport. Played with an oval-shaped ball, the game features two teams of 15 players each, determined to score points by crossing the opponent's goal line or kicking the ball through the uprights.\n\nAt its core, rugby demands a unique blend of physicality and finesse. The primary objective is to score tries, achieved by carrying the ball across the opponent's goal line, and conversions or kicks for additional points. The game unfolds through phases of play, including scrums, lineouts, and rucks, where players vie for possession and strategic advantage.\n\nPlayers pass, kick, and run with the ball, relying on teamwork and individual skill. In rugby union, the scrum and lineout are distinctive set pieces, while rugby league emphasizes a faster pace with a six-tackle possession format. Both versions share a commitment to sportsmanship and mutual respect.\n\nWhether in the grassroots of local matches or the grandeur of international competitions like the Rugby World Cup, rugby's universal appeal lies in its ability to unite players and fans alike through the exhilarating spectacle of this physically demanding yet beautifully strategic sport.")

let two_football = Sport(title: "Football", image: Image("Football"), year: "1800s", loc: "United States", 
    desc: "American football, a thrilling fusion of strategy, athleticism, and spectacle, is an integral part of the U.S. sporting landscape. Emerging from rugby and soccer influences, this uniquely American sport pits two teams of 11 players against each other, aiming to advance an oblong ball across the opponent's goal line or kick it through the goalposts.\n\nThe game involves a series of downs, each team getting four attempts to advance the ball ten yards. Through strategic plays like passes, runs, and kicks, teams aim for touchdowns or field goals, accumulating points. Defensively, players employ tackles and interceptions to thwart the opposing team's progress.\n\nCharacterized by dynamic plays, strategic huddles, and intense tackles, American football combines physical prowess with strategic complexity. The National Football League (NFL), with its iconic Super Bowl and fierce rivalries, holds a central role in this cultural phenomenon.")

let three_cricket = Sport(title: "Cricket", image: Image("Cricket"), year: "1800s", loc: "England", 
    desc: "Cricket is a captivating sport that originated in 16th-century England and has since become a global phenomenon. Played between two teams, each consisting of eleven players, cricket unfolds on an oval-shaped field with a 22-yard-long pitch at its center.\n\nThe primary objective in cricket is for the batting team to score runs, achieved by striking the ball with a bat and running between wickets. The opposing team, fielding and bowling, aims to dismiss the batsmen and restrict the runs scored. A cricket match comprises innings, with each team having a turn to bat and bowl.\n\nBowlers deliver the ball to batsmen, who attempt to score runs by hitting it into the field. The intricate strategies involve a variety of bowling techniques and batting styles. The batsmen aim to protect their wickets while strategically accumulating runs.\n\nCricket offers diverse formats, including Test matches, One Day Internationals (ODIs), and Twenty20 (T20) games, each with its unique rules and durations. The sport's timeless traditions and dynamic gameplay make cricket a source of passion for players and fans worldwide, fostering a global community that cherishes the skill, strategy, and timeless beauty of this iconic game.")

let four_wrestling = Sport(title: "Wrestling", image: Image("Wrestling"), year: "3000 BC", loc: "Ancient Greece", desc: "Wrestling, an ancient and enduring sport, epitomizes the primal struggle between opponents in a controlled arena. Rooted in both historical and modern contexts, wrestling showcases physical prowess, technique, and mental fortitude. The objective is straightforward: to pin an opponent's shoulders to the mat or accumulate points through various holds and maneuvers.\n\nContested across weight classes, wrestling ensures equitable matchups. Matches unfold in rounds, with competitors aiming for dominance through takedowns, escapes, and reversals. Points are awarded for successful moves and defensive maneuvers, with the ultimate goal of a pin or accumulating the highest score.\n\nThe heart of wrestling lies in the intensity of one-on-one combat, where athletes grapple for control and leverage. Techniques involve a combination of throws, holds, and mat wrestling, demanding a blend of strength, agility, and strategic thinking. Collegiate, freestyle, and Greco-Roman wrestling are prominent variations, each with distinct rules governing permissible moves.\n\nWrestling's global appeal is evident in its inclusion in the Olympic Games and its enduring popularity across cultures. Beyond the physicality, wrestling fosters discipline, resilience, and sportsmanship, making it not just a sport but a profound test of an athlete's character and skill.")

let five_hockey = Sport(title: "Ice Hockey", image: Image("Hockey"), year: "1800s", loc: "Canada", 
    desc: "Ice hockey, a lightning-fast collision of skill and speed, is a high-energy game played on an ice rink between two teams of six skaters each, including a goaltender. The objective is to propel a rubber puck into the opponent's goal using hockey sticks, while defending their own net from incoming shots.\n\nIce hockey is renowned for its dynamic pace, fluid teamwork, and strategic play. The rink is divided into zones, and players navigate the icy surface with speed and agility, engaging in fierce battles for puck possession. Goals are scored when the puck crosses the goal line, and the team with the most goals at the end of the game emerges victorious.\n\nThe sport is characterized by power plays, penalty kills, and fast line changes, adding layers of excitement to its unpredictable nature. Goaltenders play a crucial role, showcasing reflexes and acrobatic saves to deny the opposing team's scoring attempts. With its thrilling combination of skill, strategy, and physicality, ice hockey captivates audiences worldwide, creating an electrifying spectacle on the frozen stage.")

let six_boxing = Sport(title: "Boxing", image: Image("Boxing"), year: "3000 BC", loc: "Ancient Egypt", 
    desc: "Boxing is a riveting combat sport that traces its roots back centuries. A one-on-one contest of skill, speed, and strategy, boxing involves two fighters facing off in a roped square ring, each aiming to outmaneuver and out-punch their opponent. The objective is clear: score points by landing clean, effective blows on the opponent's upper body and head or achieve a knockout by rendering the opponent unable to continue.\n\nBoxers wear padded gloves and adhere to a set of rules that govern permissible punches, defensive techniques, and the overall conduct of the match. Bouts are typically divided into rounds, and judges score the fighters based on the quality and quantity of their punches, as well as their defensive prowess.\n\nCentral to the sport are the stances, footwork, and various punches, such as jabs, hooks, and uppercuts, which boxers use to both attack and defend. Boxing demands not only physical conditioning but also mental acuity to anticipate and counter an opponent's moves. With its mix of athleticism, strategy, and raw intensity, boxing stands as a timeless and globally celebrated sport that showcases the sheer artistry and courage of its participants.")

let seven_racing = Sport(title: "Auto Racing", image: Image("Racing"), year: "1800s", loc: "France", 
    desc: "Auto racing, a thrilling blend of speed, skill, and engineering prowess, stands as a dynamic and globally beloved sport. Whether on oval tracks, road courses, or in the challenging terrain of rally racing, the essence remains the same: drivers pushing the limits of man and machine to secure victory. The sport features a variety of vehicles, from sleek open-wheel machines to powerful stock cars, each designed for specific racing disciplines.\n\nIn auto racing, drivers compete against each other in a quest to complete a set number of laps in the shortest possible time. The diverse formats include Formula 1, NASCAR, IndyCar, and rallying, each with its unique set of rules and challenges. Races unfold with strategic pit stops, tire changes, and maneuvers to overtake opponents.\n\nDrivers must master the art of handling high-speed turns, precise braking, and strategic drafting to gain a competitive edge. The role of the team, including engineers and pit crews, is crucial for success. Victory is not only determined by the driver's speed but also by the team's ability to optimize the car's performance throughout the race.\n\nAuto racing, with its intoxicating blend of adrenaline and precision, captivates millions of fans worldwide. It remains a symbol of innovation, skill, and the pursuit of ultimate speed.")

let eight_mma = Sport(title: "Mixed Martial Arts", image: Image("MMA"), year: "650 BC", loc: "Ancient Greece", 
    desc: "Mixed Martial Arts (MMA), a dynamic and exhilarating combat sport, has surged in popularity as a true test of versatility and skill. Born from the desire to find the most effective martial art in unarmed combat, MMA combines elements of various disciplines, including striking and grappling. Fighters engage in a full-contact competition within an octagonal cage, seeking victory through a range of techniques.\n\nIn MMA, competitors utilize a blend of striking arts like boxing, Muay Thai, and kickboxing, along with grappling arts such as Brazilian Jiu-Jitsu and wrestling. The goal is to either secure a knockout, submission, or win by judges' decision. The sport demands proficiency in both standing and ground-based combat, making it a holistic test of a fighter's abilities.\n\nMatches are divided into rounds, with fighters aiming to outscore or finish their opponent within the allotted time. Fighters must adhere to rules governing strikes, submissions, and conduct, ensuring a balance between safety and the raw intensity of the competition.\n\nMMA's rise to prominence is marked by its global appeal and the emergence of organizations like the Ultimate Fighting Championship (UFC). As a captivating fusion of diverse martial arts, MMA showcases the evolution of combat sports, providing fans with high-impact, unpredictable, and physically demanding spectacles.")
